// <auto-generated />
using BusStops.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusStops.Migrations
{
    [DbContext(typeof(BusStopsContext))]
    partial class BusStopsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("BusStops.Models.Shelter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BOARDING_POINT")
                        .HasColumnType("TEXT");

                    b.Property<string>("BUS_STOP_TYPE")
                        .HasColumnType("TEXT");

                    b.Property<string>("CROSS_FALL")
                        .HasColumnType("TEXT");

                    b.Property<string>("DATE_OF_LAST_AUDIT")
                        .HasColumnType("TEXT");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("TEXT");

                    b.Property<string>("EASTING")
                        .HasColumnType("TEXT");

                    b.Property<string>("HASTUS")
                        .HasColumnType("TEXT");

                    b.Property<string>("LATITUDE")
                        .HasColumnType("TEXT");

                    b.Property<string>("LONGITUDE")
                        .HasColumnType("TEXT");

                    b.Property<string>("NEAREST_CROSS_STREET")
                        .HasColumnType("TEXT");

                    b.Property<string>("NORTHING")
                        .HasColumnType("TEXT");

                    b.Property<int>("OBJECTID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ROAD_GRADIENT")
                        .HasColumnType("TEXT");

                    b.Property<string>("STREETNAME")
                        .HasColumnType("TEXT");

                    b.Property<string>("SUBURB")
                        .HasColumnType("TEXT");

                    b.Property<string>("TACTILE_GROUND_SURF_INDICAT_Y_N")
                        .HasColumnType("TEXT");

                    b.Property<string>("geo_point_2d")
                        .HasColumnType("TEXT");

                    b.Property<string>("geo_shape")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shelter");
                });
#pragma warning restore 612, 618
        }
    }
}
